/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SpoilerSpan {
        /**
          * Target particle density (particles per 100 square pixels)
          * @default 8
         */
        "density": number;
        /**
          * Target frames per second for particle animation (default: 60). Lower values improve performance on slower devices.
          * @default 60
         */
        "fps": number;
        /**
          * Maximum velocity for particles (pixels per frame)
          * @default 0.05
         */
        "maxVelocity": number;
        /**
          * Minimum velocity for particles (pixels per frame)
          * @default 0.01
         */
        "minVelocity": number;
        /**
          * Enable continuous position monitoring for hover effects and CSS transforms. When false, position updates only on scroll/resize events (better performance). When true, uses RAF loop to track position changes every frame (handles transforms/animations).
          * @default false
         */
        "monitorPosition": boolean;
        /**
          * Particle lifetime in frames (60fps = 1 second per 60 frames)
          * @default 120
         */
        "particleLifetime": number;
        /**
          * Text fade-in duration in milliseconds when revealing
          * @default 300
         */
        "revealDuration": number;
        /**
          * Scale factor for particle size
          * @default 1
         */
        "scale": number;
        /**
          * Delay in milliseconds before stopping particle spawning after click (default: 300ms)
          * @default 0
         */
        "spawnStopDelay": number;
    }
}
declare global {
    interface HTMLSpoilerSpanElement extends Components.SpoilerSpan, HTMLStencilElement {
    }
    var HTMLSpoilerSpanElement: {
        prototype: HTMLSpoilerSpanElement;
        new (): HTMLSpoilerSpanElement;
    };
    interface HTMLElementTagNameMap {
        "spoiler-span": HTMLSpoilerSpanElement;
    }
}
declare namespace LocalJSX {
    interface SpoilerSpan {
        /**
          * Target particle density (particles per 100 square pixels)
          * @default 8
         */
        "density"?: number;
        /**
          * Target frames per second for particle animation (default: 60). Lower values improve performance on slower devices.
          * @default 60
         */
        "fps"?: number;
        /**
          * Maximum velocity for particles (pixels per frame)
          * @default 0.05
         */
        "maxVelocity"?: number;
        /**
          * Minimum velocity for particles (pixels per frame)
          * @default 0.01
         */
        "minVelocity"?: number;
        /**
          * Enable continuous position monitoring for hover effects and CSS transforms. When false, position updates only on scroll/resize events (better performance). When true, uses RAF loop to track position changes every frame (handles transforms/animations).
          * @default false
         */
        "monitorPosition"?: boolean;
        /**
          * Particle lifetime in frames (60fps = 1 second per 60 frames)
          * @default 120
         */
        "particleLifetime"?: number;
        /**
          * Text fade-in duration in milliseconds when revealing
          * @default 300
         */
        "revealDuration"?: number;
        /**
          * Scale factor for particle size
          * @default 1
         */
        "scale"?: number;
        /**
          * Delay in milliseconds before stopping particle spawning after click (default: 300ms)
          * @default 0
         */
        "spawnStopDelay"?: number;
    }

    interface SpoilerSpanAttributes {
        "scale": number;
        "minVelocity": number;
        "maxVelocity": number;
        "particleLifetime": number;
        "density": number;
        "revealDuration": number;
        "spawnStopDelay": number;
        "monitorPosition": boolean;
        "fps": number;
    }

    interface IntrinsicElements {
        "spoiler-span": Omit<SpoilerSpan, keyof SpoilerSpanAttributes> & { [K in keyof SpoilerSpan & keyof SpoilerSpanAttributes]?: SpoilerSpan[K] } & { [K in keyof SpoilerSpan & keyof SpoilerSpanAttributes as `attr:${K}`]?: SpoilerSpanAttributes[K] } & { [K in keyof SpoilerSpan & keyof SpoilerSpanAttributes as `prop:${K}`]?: SpoilerSpan[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "spoiler-span": LocalJSX.IntrinsicElements["spoiler-span"] & JSXBase.HTMLAttributes<HTMLSpoilerSpanElement>;
        }
    }
}
