import { cp, mkdir, rm } from 'node:fs/promises';
await rm('dist', { recursive: true, force: true });
await mkdir('dist', { recursive: true });
await cp('public', 'dist', { recursive: true });
for (const file of ['index.html', 'styles.css', 'app.js', 'sound-effects.js', 'icon-interactions.js', 'page-reveal.js', 'i18n.js', 'translations.js']) await cp(file, `dist/${file}`);
await mkdir('dist/yandex-lavka', { recursive: true });
for (const file of ['index.html', 'case.css', 'case.js', 'content.js', 'reader-interaction.js']) await cp(`Yandex Lavka/${file}`, `dist/yandex-lavka/${file}`);
console.log('Built portfolio in dist/');
await mkdir('dist/t-bank',{recursive:true});
for (const file of ['index.html','case.css','case.js','spoiler.js','text-spoiler.js','text-particles.js']) await cp(`T-Bank/${file}`, `dist/t-bank/${file}`);
