import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { mkdtemp,writeFile,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomBytes,scryptSync } from 'node:crypto';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
const temp=await mkdtemp(join(tmpdir(),'tbank-test-'));
const password='test-only-password';const salt=randomBytes(16).toString('hex');
const auth=join(temp,'auth.json');
await writeFile(auth,JSON.stringify({salt,hash:scryptSync(password,salt,64).toString('hex'),secret:randomBytes(32).toString('hex')}));
const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'5199',TBANK_AUTH_FILE:auth},stdio:['ignore','pipe','inherit']});
await once(server.stdout,'data');
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const page=await browser.newPage({viewport:{width:1200,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const requested=[];page.on('request',r=>requested.push(r.url()));
const base='http://localhost:5199';
try {
 await page.goto(base);await page.locator('a[data-link=tbank]').click();await page.waitForURL('**/t-bank/');
 await page.waitForFunction(()=>document.querySelectorAll('.bank-media .dots .dot').length===900);
 assert.equal(await page.locator('.bank-tabs').isVisible(),false);
 assert.ok((await page.locator('.bank-intro').innerText()).includes('launched 12 projects'));
 assert.equal(requested.some(url=>url.includes('/api/tbank/media/')),false);
 for(const path of ['/api/tbank/media/profileDesktop-1-1.png','/api/tbank/cases/main'])assert.equal((await page.request.get(base+path)).status(),401);
 for(const path of ['/.private/tbank/media/profileDesktop-1-1.png','/.data/tbank-auth.json'])assert.equal((await page.request.get(base+path)).status(),403);
 await page.screenshot({path:'.private/tbank/verification/locked-desktop.png',fullPage:true});
 assert.equal(await page.locator('.text-spoiler').count(),10);
 assert.equal(await page.locator('.desktop-caption h2').first().evaluate(el=>getComputedStyle(el).visibility),'hidden');
 await page.locator('.desktop-caption .spoiler-trigger').first().click();
 assert.equal(await page.locator('#case-password').evaluate(el=>el===document.activeElement),true);
 assert.equal(await page.locator('#case-password').getAttribute('type'),'password');
 assert.equal(await page.locator('#case-password').evaluate(el=>getComputedStyle(el).outlineStyle),'none');
 assert.equal(await page.locator('#case-password').evaluate(el=>getComputedStyle(el,'::placeholder').opacity),'0');
 assert.equal(await page.locator('dialog').count(),0);
 await page.locator('#case-password').fill('wrong');await page.locator('#case-password').press('Enter');
 await page.waitForFunction(()=>document.querySelector('#case-password').value==='' && !document.querySelector('#password-form').hasAttribute('aria-busy'));
 assert.equal(await page.locator('[role=alert]').count(),0);
 assert.equal(await page.locator('.spoiler--open').count(),0);
 await page.locator('#case-password').fill(password);await page.locator('#case-password').press('Enter');
 await page.waitForFunction(()=>document.querySelectorAll('.bank-media.spoiler--open').length===6 && document.querySelectorAll('.text-spoiler.spoiler--open').length===10);
 assert.equal(await page.locator('.desktop-caption h2').first().evaluate(el=>getComputedStyle(el).visibility),'visible');
 assert.equal(await page.getByRole('tab',{name:'Profile',exact:true}).evaluate(el=>el.matches(':focus-visible')),false);
 assert.ok((await page.locator('.spoiler picture img').first().getAttribute('src')).endsWith('.svg'));
 assert.equal(await page.getByRole('tab',{name:'Quizi'}).isDisabled(),true);
 assert.equal(await page.locator('#password-form').isVisible(),false);
 assert.ok((await page.locator('.bank-intro').innerText()).includes('8K users daily'));
 await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.bank-media .dots .dot').length===900);
 assert.equal(await page.locator('.spoiler--open').count(),0);
 assert.equal(await page.locator('.bank-tabs').isVisible(),false);
 assert.ok((await page.locator('.bank-intro').innerText()).includes('launched 12 projects'));
 assert.equal((await page.request.get(base+'/api/tbank/media/profileDesktop-1-1.png')).status(),401);
 assert.equal(await page.locator('#case-password').inputValue(),'');
 await page.locator('#case-password').fill(password);await page.locator('#case-password').press('Enter');
 await page.waitForFunction(()=>document.querySelectorAll('.bank-media.spoiler--open').length===6 && document.querySelectorAll('.text-spoiler.spoiler--open').length===10);
 await page.waitForFunction(()=>[...document.querySelectorAll('.blur-block')].every(el=>getComputedStyle(el).opacity==='0'));
 const layouts=[];
 for(const width of [1200,375,320,768,1024]) {
  await page.setViewportSize({width,height:900});
  await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));});
  const geometry=await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,profileHeight:document.querySelector('.profile').offsetHeight}));
  assert.equal(geometry.width,width);layouts.push(geometry);
  if([1200,375].includes(width))await page.screenshot({path:`.private/tbank/verification/browser-profile-${width}.png`,fullPage:true});
 }
 await page.getByRole('tab',{name:'Main 8.4'}).click();
 await page.waitForFunction(()=>!document.querySelector('#main-cases').hidden);
 assert.ok((await page.locator('.bank-intro').innerText()).includes('scheduled for Q1'));
 await page.waitForFunction(()=>document.querySelector('#main-cases video')?.readyState>=2);
 for(const width of [1200,375]) {
  await page.setViewportSize({width,height:900});
  await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  await page.evaluate(async()=>{for(const i of document.images)i.loading='eager';await Promise.all([...document.images].map(i=>i.decode()));});
  await page.screenshot({path:`.private/tbank/verification/browser-main-${width}.png`,fullPage:true});
 }
 await page.getByRole('tab',{name:'Main 8.4'}).press('ArrowLeft');
 await page.waitForFunction(()=>!document.querySelector('#profile-cases').hidden);
 assert.equal(await page.locator('.case-close').getAttribute('href'),'/');
 const touch=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true});
 const phone=await touch.newPage();await phone.goto(base+'/t-bank/');
 await phone.locator('#case-password').tap();await phone.locator('#case-password').fill(password);
 await phone.locator('#case-password').press('Enter');
 await phone.waitForFunction(()=>document.querySelectorAll('.bank-media.spoiler--open').length===6 && document.querySelectorAll('.text-spoiler.spoiler--open').length===10);
 await phone.getByRole('tab',{name:'Main 8.4'}).tap();await phone.waitForFunction(()=>!document.querySelector('#main-cases').hidden);
 await touch.close();
 assert.deepEqual(errors,[]);
 const report={errors,layouts,passwordGate:true,protectedAssets:true,wrongPasswordRejected:true,reloadResetsSpoilersAndSession:true,focusHidesPlaceholderWithoutOutline:true,profileAndMainTabs:true,quiziDisabled:true,originalVideo:true};
 await writeFile('verification/tbank-checks.json',JSON.stringify(report,null,2));console.log(report);
} finally {await browser.close();const exited=once(server,'exit');server.kill();await exited;await rm(temp,{recursive:true,force:true});}
